/*
//  Simple Base Library for C++ (libsimple-base)
//  Copyright (c) 2010-2013, Adam Rehn
//
//  ---
//
//  Checksum Calculation Functions
//
//  The functions here wrap around third party implementations of checksum
//  functions for use with files and arbitrary data.
//
//  ---
//
//  This file is part of the Simple Base Library for C++ (libsimple-base).
//
//  libsimple-base is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as published
//  by the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public License
//  along with libsimple-base. If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef _LIB_SIMPLE_BASE_CHECKSUM_H
#define _LIB_SIMPLE_BASE_CHECKSUM_H

#include <string>
#include <fstream>
#include <stdint.h>
#include <cstring>
using std::string;
using std::ifstream;
using std::ios;

//CRC32 implementation generated by pycrc
uint32_t crc32(const string& path);
uint32_t crc32(ifstream& infile);
uint32_t crc32(const char *data, unsigned int length);

//Use this for working with memory that you are writing to file as you go
uint32_t crc32_cumulative(uint32_t crc, char* data = NULL, unsigned int length = 0);

//SHA-1 implementation by Paul E. Jones <paulej@packetizer.com>
string sha1(const string& data);           //Just a wrapper for the other version of this function.
string sha1(const char *data, int length); //Calculates the hex string form of a SHA-1 Message Digest.

string sha1_file(const string& file);      //Calculates the SHA-1 checksum of an entire file.

//Generate the raw binary SHA-1 checksum for a file
void sha1_file_raw(const string& file, unsigned int checksum[5]);
void sha1_file_raw(ifstream& infile, unsigned int checksum[5]);

#endif
